<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>data2410_api_v1</RootNamespace>
    <UserSecretsId>74e97ecc-d31e-4c4e-bc37-72ed8f5bec6b</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="MySql.Data" Version="9.6.0" />
    <PackageReference Include="MySql.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="MySqlConnector" Version="2.5.0" />
    <PackageReference Include="Scalar.AspNetCore" Version="2.13.20" />
  </ItemGroup>

</Project>
